### PR TITLE
Added .25 and .75 Animation scales to the 3 developer animation options

### PR DESCRIPTION
**Pull request by brentluna**
I added .25 and .75 animation scales to the array options. It's been a while since I've looked at android code, but I believe that's all that is needed.

 If you are against this change, sorry for wasting your time.

### CODE REVIEW

**Comment by ApertureAndroid** [comment]
Pretty sure this already is possible because of this commit: https://github.com/PureNexusProject/android_packages_apps_Settings/commit/4454cfad12f27071fe38a1d498ff5f58a113f6d7.

**Comment by brentluna** [comment]
@ApertureAndroid hmm, it does look like that should be the range seekbar for animation scale, however i'm only seeing the list with the 0, .5, 1, 10 options.  Do you have the seekbar?

**Comment by ApertureAndroid** [comment]
@brentluna The commit was added after the first PN N build, so you'll only get the seekbar in the next build or if you cook up a homemade build.

**Comment by brentluna** [comment]
Closed, as it looks like seekbar was already merged.

**Pull request closed without merging**
